### ISSUE TITLE
Templates for backend modifications?

### ISSUE THREAD

**Issue by OndeVai** [Sitefinity/Sitefinity-VSIX#6]
Will there be templates to modify the backend like in Thunder? IE custom fields, etc?

**Comment by pfilipov** [comment]
Hi @OndeVai,

We are currently planning different features for v2, please log you idea as [described here](https://github.com/Sitefinity/Sitefinity-VSIX/blob/master/CONTRIBUTING.md#requesting-new-features). Keep in mind that Sitefinity 11.0 is coming with new Admin Panel concept and the implementation there is a little bit different read [more here](https://www.sitefinity.com/blogs/peter-filipov-blog/2018/05/30/how-to-extend-the-new-sitefinity-admin-app). Our ultimate goal is to provide that kind of functionality in the Sitefinity VSIX out of the box.

Peter
