### ISSUE TITLE
sf.exe has stopped working

### ISSUE THREAD

**Issue by FerdiNebi** [Sitefinity/Sitefinity-VSIX#7]
After installation of the extension on VS 2017 or VS 2015, when I open a solution I get an error saying "sf.exe has stopped working" and then the Studio crashes.

**Comment by alekgallo** [comment]
I am getting the same issue on VS 2017 community edition.

**Comment by asocratous** [comment]
Hello,

I have the same issue here, both on Visual Studio 2017 and 2015. When I disable the Sitefinity VSIX extension, the solutions open without a problem.

**Comment by gg3orgiev** [comment]
This should be resolved by installing .NET Core before installing the extension. There is Note in the README. 
Note: For Visual Studio 2015 and 2017 (up to Update 15.3) you first need to install https://www.microsoft.com/net/download/windows before using the extension.
