### ISSUE TITLE
Project Not refreshed after adding widget

### ISSUE THREAD

**Issue by jonathanread** [Sitefinity/Sitefinity-VSIX#8]
**Steps to reproduce**
- Right Click MVC Folder
- Add Sitefinity Widget

Widget files do not immediately show in project

**Expected Results**
The expected result would be for the VSIX to refresh the project so the user can see the new files added.

**Comment by Novkirishki** [comment]
Hi Jonathan,
this is a known limitation for the current version. It is one of the things we will be implementing in some of the future versions.

**Comment by annix8** [comment]
Hello Jonathan,

We have introduced this functionality in the Sitefinity-CLI - version 1.0.0.7 which was released on Jun 18.

Regards
