### ISSUE TITLE
No Support for 11.1 or 11.2?

### ISSUE THREAD

**Issue by xantari** [Sitefinity/Sitefinity-VSIX#9]
This page says it only works with 10.2 and 11.0:
https://marketplace.visualstudio.com/items?itemName=vs-publisher-443.Sitefinity-VSIX

**Comment by chiphunt1** [comment]
I see the same thing. Very disappointed Sitefinity is already at version 12 and VSIX is not even up to 11.1 or 11.2 yet.

**Comment by Novkirishki** [comment]
Sitefinity VSIX and Sitefinity CLI support versions from 10.2 up to the latest. The VSIX page in the marketplace (https://marketplace.visualstudio.com/items?itemName=vs-publisher-443.Sitefinity-VSIX) was not updated, which is now fixed.
